pagopa/github-actions-template

- semver-setup/action.yml
> fix semver-setup

- aks-deploy/action.yml
> fix: Commit for triggering release

- aks-deploy/action.yml
- maven-release/README.md
- maven-release/action.yml
- maven-semver/action.yml
> fix: Removed beta

- maven-release/README.md
- maven-release/action.yml
- maven-semver/README.md
- maven-semver/action.yml
handle beta inputs for canary deployment
> feat: Canary

- node-release/README.md
- node-release/action.yml
template for release and deploy for nodeJS
> feat: Node

- node-release/action.yml
> fix: Node Release

- .github/workflows/release.yml
- node-release/action.yml
> fix: Trigger

- node-semver-setup/action.yml
> fix: solved missing bash shell indication

- node-semver-setup/action.yml
> fix: add input for semver

- helm-bump/README.md
- helm-bump/action.yml
- maven-semver/action.yml
- node-release/README.md
- node-release/action.yml
> chore: Helm bump

- nodo5-semver-setup/action.yml
> feat: Added more checks on semver generation

- maven-release/README.md
- maven-release/action.yml
- removed beta as required and set fase as default
> fix: Beta not required

- aks-deploy/README.md
- aks-deploy/action.yml
> chore: Timer helm deploy

- maven-release/README.md
- maven-release/action.yml
- maven-semver/README.md
- maven-semver/action.yml
- Update `maven-release` action and `semver` action to add JDK 17 compatibility
- in this [PR](https://github.com/pagopa/pagopa-gpd-upload/pull/2) during `pagopa-gpd-upload` release and deploy
> refactoring: Update semver action for JDK version 17

- node-release/action.yml
🔨 fix `node-release`:
if you selected `skip` the output was empty
> fix: Node release output

- maven-release/action.yml
- sbt-release/action.yml
- sbt-semver/action.yml
added sbt-release and sbt-semver files for scala projects using sbt
> feat: Scala sbt release action

- sbt-release/README.md
- sbt-semver/README.md
- sbt-semver/action.yml
fix version increment in sbt semver + readmes
> fix: Fix version increment @ new release

- maven-release/README.md
- maven-release/action.yml
prelease input for release template
> feat: Prelease

- maven-release/README.md
- maven-release/action.yml
- node-release/README.md
- node-release/action.yml
> feat: Node Release

- maven-release/action.yml
- node-release/action.yml
> fix: Update gh release

- nodo5-semver-setup/action.yml
> Fix Nodo5 semver setup

- maven-release/action.yml
- node-release/action.yml
the input `skip_ci` doesn't work as you excepted in `node_release` and `maven_release` templates.
This PR fix this bug 🐛
> fix: This is a bugfix for `skip_ci`

- maven-release/README.md
- maven-release/action.yml
- node-release/README.md
- node-release/action.yml
> feat: Create only tag

- maven-release/action.yml
> fix: Maven Release

- .github/workflows/release.yml
> feat: Updated Release action

- .github/workflows/release.yml
> fix: release action with workload dispatch

- payments-flow-docker-snapshot/README.md
- payments-flow-docker-snapshot/action.yml
> fix: changed name from spac-flow-docker-snapshot to payments-flow-docker-snapshot

- payments-flow-docker-snapshot/action.yml
- payments-flow-release/README.md
- payments-flow-release/action.yml
> feat: Added Payments-release

- payments-flow-docker-snapshot/action.yml
- payments-flow-release/action.yml
Use pagopa/azure-pipelines action to trigger azdo
> feat: Update trigger azdo for payments actions

- payments-flow-release/action.yml
> fix: Payments release added v prefix for docker

- helm-bump/action.yml
> feat(action.yml): update canaryDelivery image tag key

- maven-package/action.yml
- Bump actions/cache version to 4.2
[PIDM-199](https://pagopa.atlassian.net/browse/PIDM-199?atlOrigin=eyJpIjoiMmNiODZmZjJjYTg3NGQ1NDk5MGI2MWQ5YmU4MjdkZTEiLCJwIjoiaiJ9)
[PIDM-199]: https://pagopa.atlassian.net/browse/PIDM-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [PIDM-199] Bump actions/cache version to 4.2
